change condition

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,11 +21,10 @@ jobs:
           regex: '#username=(\w+)'
       - name: Extracted username not exist
         run: |
-          echo "${{ steps.username-match.outputs.group1 }}"
-        if: ${{ steps.username-match.outputs.group1 == '' }}
-        shell: bash
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          if [ "${{ steps.username-match.outputs.group1 }}" = "" ]; then
+            echo "::error::Username not defined"
+            exit 1
+          fi
       - uses: actions-ecosystem/action-regex-match@v2.0.2
         id: database-match
         with:
@@ -33,7 +32,7 @@ jobs:
           regex: '#database=(\w+)'
       - name: Extracted database exist
         run: |
-          echo "${{ steps.database-match.outputs.group1 }}"
+          echo "Error: ${{ steps.database-match.outputs.group1 }}"
         if: ${{ steps.database-match.outputs.group1 == '' }}
         shell: bash
         env:
